### ISSUE TITLE
Installation instructions a bit unclear

### ISSUE THREAD

**Issue by veghp** [barricklab/pLannotate#10]
Great tool, thanks for putting it together.

I have a few comments regarding the readme:
- the 'releases' link leads to the first release which does not have a blast database
- gunzipping the blast database results in a BLAST_dbs folder which also has another BLAST_dbs folder in it -- maybe it's helpful to clarify which needs to be in the pLannotate folder
- a step missing after activating the Conda environment: we need to install the package
- the command line batch example does not work without also specifying the path to the database with `-b`

**Comment by splaisan** [comment]
HI,
Maybe you could add a link to the DB archive in the ReadMe
https://github.com/barricklab/pLannotate/releases/download/v1.0.3/BLAST_dbs.tar.gz
Thanks

**Comment by mmcguffi** [comment]
Hi @splaisan -- I added a [new release](https://github.com/barricklab/pLannotate/releases/tag/v1.1.0) today, with significant improvements and better installation instructions (along with the readme now pointing to the correct release :))

Please let me know if you have any issues.
