### ISSUE TITLE
Entry size is too large -- must be 50000 bases or less

### ISSUE THREAD

**Issue by Nirmal2310** [barricklab/pLannotate#19]
Hi @mmcguffi,
I am trying to annotate plasmids using this tool. So far it had worked pretty well but it is throwing error for plasmids larger than 50Kb. I tried the method mentioned in one of the issue which was building the tool from the source but it is still throwing me the same error. I tried manipulating the script a bit but it didn't gave the expected result. 
So I request you to please help me out whenever its possible.
Please let me know if you need any other information from my side.
Thank you in advance.

**Comment by mmcguffi** [comment]
Hi @Nirmal2310,

It's my understanding that this is for a metagenomics pipeline? I might suggest a tool like [prokka](https://github.com/tseemann/prokka) or [bakta](https://github.com/oschwengers/bakta), both of which will likely provide a better, more complete annotation for that kind of data. pLannotate is designed with the assumption that the DNA is engineered, so the databases and filtering methods applied extend from that assumption. Some of this is also discussed in #14 

That said, if you wish to use pLannotate on plasmids larger than 50,000 bp you will need to clone the repository, create a conda env, install it as a package, and download the database. It seems there are currently some issues here though, making it a bit annoying (sorry!). I need to get a new version of this out on Bioconda, but in the meantime, this should work:

```bash
git clone --depth 1 --branch master https://github.com/barricklab/pLannotate.git
cd pLannotate

mamba env create -f environment.yml
mamba activate plannotate
# downgrade to a streamlit version that still works
mamba install streamlit=1.2.0

# fix the requirements.txt by simply overwriting it
echo "" > requirements.txt
pip install . --no-deps -vv

plannotate setupdb

plannotate streamlit
```

Let me know if you run into any issues!
Matt

**Comment by Nirmal2310** [comment]
Hi @mmcguffi,
Thank you replying on such short notice. So I tried installing and running pLannotate with the steps you mentioned above but now I am getting a new error: 
FileNotFoundError: [Errno 2] No such file or directory: '7600-SR-001_1_length_63547_plannotate/7600-SR-001_1_length_63547_pLann.gbk'
Please help me out with this error.
Thank you in advance

**Comment by mmcguffi** [comment]
Please write the commands you have used here as well as OS. It looks like you are trying to path to a file that doesn't exist

**Comment by Nirmal2310** [comment]
Hi @mmcguffi ,
I tried the following command on ubuntu 18.04 OS:
```bash
plannotate batch -i 7600-SR-001_1_length_63547.fasta -o 7600-SR-001_1_length_63547_plannotate --html
```

**Comment by mmcguffi** [comment]
`-o` is the output folder. pLannotate does not make this by default, so I assume that the directory`001_1_length_63547_plannotate` does not exist

**Comment by Nirmal2310** [comment]
Hi @mmcguffi 
I tried running plannotate without using -o argument and it is running perfectly. Thank you so much for your time and help. I am closing this issue with this comment.
Once again thank you very much.
