### ISSUE TITLE
batch mode

### ISSUE THREAD

**Issue by jurquiza** [barricklab/pLannotate#2]
Would be great if for the local installation it could be possible to process files in batch mode. Some instructions to do it would be cool. 

Another thing will good if users could create their own add on database, some of the parts we use in our lab are not picked up

I so far managed to run it within Docker, however could facilitate portability if there is a full docker implementation of the tool. However im so far impressed with the tool and very thankful that you developed such a cool tool.

**Comment by mmcguffi** [comment]
Hi Uriel, thanks so much for your feedback. I have a rough command line wrapper I have written for pLannotate for batch processing, and I also want to include custom databases like you suggested.

I'll clean up the command line script and get it out soon-ish with some documentation, though I have to do some fairly significant code cleanup and refactoring to robustly support custom databases, so that will take a little longer.

Support for more robust environments like Docker and/or distribution from pip or conda is also on the list, and I hope to get that out as well.

**Comment by cjw85** [comment]
@mmcguffi 

Have you made any progress on your refactoring? We (Oxford Nanopore Technologies) would like to use your parsing an plotting code within some Nextflow workflows. We don't mind doing the leg-work to refactor the project into a standardised python package with a command-line (batch) entry point in addition to the web-server entry-point.

**Comment by cjw85** [comment]
@mmcguffi I just look the liberty to refactor the code to create a standard Python package. I've tried to keep the changes as minimal as possible. See https://github.com/barricklab/pLannotate/pull/3

**Comment by mmcguffi** [comment]
@cjw85 thanks again for the pull request. Currently there is no plot-saving functionality implemented, as Bokeh (the plotting library used here) requires internet browser drivers to create png files, which seems like a strange overhead to require for pLannotate. Would simply saving the plots as HTML work for your needs?

**Comment by cjw85** [comment]
We'd like to use pLannotate plots within some of our workflow reports, so access to the function returning the bokeh plot instance is all we require.

We have quite a bit of experience using [bokeh embed](https://docs.bokeh.org/en/latest/docs/user_guide/embed.html) for creating standalone HTML documents with our [aplanat report](https://github.com/epi2me-labs/aplanat/blob/master/aplanat/report.py) templates.

**Comment by mmcguffi** [comment]
@cjw85 @jurquiza I've implemented a barebones CLI, with some sparse documentation (thanks for the great help again @cjw85 !). Currently it does not accept input from `stdin`, which may be a desired feature. I will open a new issue for adding custom databases -- the code is currently bespoke for each database, and I need to refactor the code to make adding new databases simple and modular.

**Comment by jurquiza** [comment]
Hey amazing that you made the batch interface, i will start using it now I will give you feedback if anything comes up

**Comment by mmcguffi** [comment]
@jurquiza I released [v1.1.0](https://github.com/barricklab/pLannotate/releases/tag/v1.1.0) today, and the command line interface is now a bit more robust with more features. Please let me know if you have any feedback with this new version :)
