### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'cli'

### ISSUE THREAD

**Issue by mcrone** [barricklab/pLannotate#20]
Found this error while trying a local install. This seems to have been caused by an update to streamlit and so I found and used the solution here: [https://github.com/streamlit/streamlit/issues/5146#issuecomment-1223306586](https://github.com/streamlit/streamlit/issues/5146#issuecomment-1223306586)

The change required is to change all references to `streamlit.cli` to `streamlit.web.cli`

**Comment by mmcguffi** [comment]
Thanks Michael -- I need push some updates to pLannotate and lock in a few versions of Streamlit that work
