### ISSUE TITLE
Input file size

### ISSUE THREAD

**Issue by idolawoye** [barricklab/pLannotate#30]
Hi,

I found plannotate to be very useful for my work but I am struggling to get it work for larger plasmids > 50,000bp. Is there a workaround for this situation or can you recommend another tool to explore that option?

Thanks!

**Comment by mmcguffi** [comment]
Hi @idolawoye Im glad you have found it useful! This will likely always be a limitation for the web server version, but this feature is available for the CLI. I believe that you will have to do a manual installation from the current master branch to get this functionality. I plan on pushing an update to pLannotate soon so this and other fixes are available via conda, but I'm currently moving across the country so this won't be available immediately. 

One thing I caution everyone trying to annotate plasmids larger than 50,000 bp though, is that engineered plasmids are rarely larger than this size -- I would double check that pLannotate is the correct tool for your purposes

**Comment by mmcguffi** [comment]
See #14 and #19
