### ISSUE TITLE
annotations start one base pair too late when reverse

### ISSUE THREAD

**Issue by dr3y** [barricklab/pLannotate#9]
Just installed this great software but noticed a weird problem! All my reverse annotations are starting one base pair later than they should be.
reverse:
![image](https://user-images.githubusercontent.com/3620565/138654773-648cfde5-a092-4898-805d-6c8aa605ab61.png)
forward:
![image](https://user-images.githubusercontent.com/3620565/138654832-02364b1b-135b-471b-9952-91958d053d4c.png)

here is an example sequence: https://gist.github.com/dr3y/b3eac9953cb4808fb875d2d273d2ebe3

**Comment by mmcguffi** [comment]
Fixed in [v1.1.0](https://github.com/barricklab/pLannotate/releases/tag/v1.1.0)
